services:
  telemetry-api:
    build:
      context: .
    image: mkurd47/telemetry-stream-api:1.0
    container_name: telemetry-stream-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:////app/data/telemetry.db
    volumes:
      - telemetry-data:/app/data
    restart: unless-stopped

volumes:
  telemetry-data: